file_format: "1"
id: enki42
name: The enki42 
type: shield
url: https://github.com/benvallack/zmk-config-enki42
requires: [pro_micro]
exposes: [i2c_oled]
features:
  - keys
siblings:
  - enki42_left
  - enki42_right
  - enki42_dongle
